var stringConstatnts = {
    contentPicDefaultUrl: "/Images/Content-Default.png",
    profilePicDefaultUrl: "/Images/up.png",
    unsupprtedFileType: "You have uploaded wrong file type please upload .jpg,.jpeg,.png,.gif file.",
    lectureRequired: "Lecture Name is Required.",
    lectureexist: "Lecture name is already exist in this course.",
    sectionRequired: "Section Name is Required.",
    sectionExist: "Section name is already exist in this lecture.",
    minLectureValidation: "Course Should have atleast one Lecture.",
    minContentValidation: "should have atleast one Content.",
    minSectionValidation: "should have atleast one section.",
    unsupportedDocFileMsg: "You have uploaded wrong file type please upload only .doc,.docx,.txt file.",
    unsupportedMovieFileMsg: "You have uploaded wrong file type please upload only.mp4, .flv,.webm file.",
    unsupportedImageFileMsg: "You have uploaded wrong file type please upload only .jpg,.jpeg,.png,.gif file.",
    movieSuggestionMsg: "You can upload .mp4, .flv,.webm file (File size limit is 1 GB) Or enter Youtube URL.",
    docSuggestionMsg: "You can upload .doc,.docx,.txt file (File size limit is 8 MB).",
    imageSuggestionMsg: "You can upload .jpg,.jpeg,.png,.gif file (File size limit is 8 MB).",
    interactiveQuestionRequired: "Question text is required.",
    interactiveOptionRequired: "Option text is required.",
    textEditor: "textEditor",
    video: "video",
    image: "image",
    profile: "profile",
    elearning: "ELearning",
    createELearningContentStep1: "1/ELearning/CreateCourse",
    createELearningContentStep2: "2/ELearning/CreateCourse",
    defaultPath: "/CourseList",
    defaultHref: "#/CourseList",
    profilePagePath: "/Profile",
    errorMessage: "No data found.",
    saveError: "Can not save data",
    getError: "Can not get Information",
    deleteError: "Can not delete data",
    topicNameRequiredMsg: "Topic Name is required",
    canNotDelete: "This operation could not be performed,",
    exceptionMessage: "There is some server error, so action could not be performed at a moment. Please try after some time.",
    imageFileSupportedExtension: "image/png,image/jpeg,image/jpg,image/gif",
    maxFileSizeLimit: "You have uploaded more than 8 MB.",
    maxFileSizeLimitForVideo: "You have uploaded more than 1 GB.",
    invalidLink: "Invalid URL",
    youtubeLinkRequired: "Youtube link is required",
    editorContentRequired: "Editor text is required",
    catchErrorMessage: "There is some server error, so action could not be performed at a moment. Please try after some time ?",
    serverErrorMessage: "Sorry, an error has occurred in attempting to retrieve results. Please try reloading the page.",
    authorizedErrorMessage: "You are not authorized person to access this page.",
    videoTooltip: "To upload file or add youtube link please enter Topic name.",
    imageTooltip: "To Upload File please enter Topic Name.",
    lectureDelete: "Your Lecture has been deleted successfully.",
    sectionDelete: "Your Section has been deleted successfully.",
    sectionPageDelete: "Your Section Content has been deleted successfully.",
    contentDelete: "Your course has been deleted successfully.",
    closeSectionPagePanelMsg: "You need to close opened content panel, to open another one."
};
//# sourceMappingURL=StringConstants.js.map